### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by pro4esor**

### CODE REVIEW

**Comment by serartmar** [comment]
@pro4esor please fix errors that you get in a console. Some of them are causing the app to crash:
image

**Comment by serartmar** [comment]
image

**Comment by serartmar** [comment]
> Does it even work? I guess `large` should be nested inside the breakpoints object
> image

**Comment by pro4esor** [comment]
> I guess this block is shifted to the right side a bit 🙂 :
> image
> 
> Also make sure that a dark block with call to actions looks well in Safari. And I guess you missed the yellow shadow beneath that block 🙂 :
> image
> 
> Also make sure that on iPads the site looks well:
> image
> image

**Pull request merged**
